CREATE TABLE [dbo].[UPDATE_USER]
(
	[USERID] INT NOT NULL PRIMARY KEY, 
    [USERNAME] NCHAR(20) NOT NULL, 
    [PWD] NCHAR(20) NOT NULL, 
    [ROLE] NCHAR(10) NOT NULL, 
    [STATUS] NCHAR(10) NOT NULL
)
